name: Update NYC Zoning Data

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-zoning-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.15'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pdfplumber==0.7.6'
          
      - name: Download PDFs
        run: |
          mkdir -p pdfs
          cd pdfs
          
          # Define array of PDF URLs
          URLS=(
            "https://zr.planning.nyc.gov/sites/default/files/article/32/Article%20I.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/39/Article%20II.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/40/Article%20III.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/41/Article%20IV.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/42/Article%20V.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/62/Article%20VI.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/139/Article%20VII.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/140/Article%20VIII.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/141/Article%20IX.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/142/Article%20X.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/143/Article%20XI.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/144/Article%20XII.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/145/Article%20XIII.pdf"
            "https://zr.planning.nyc.gov/sites/default/files/article/146/Article%20XIV.pdf"
          )
          
          # Download each PDF with proper naming
          for i in "${!URLS[@]}"; do
            article_num=$(($i + 1))
            formatted_num=$(printf "%02d" $article_num)
            echo "Downloading Article ${formatted_num}..."
            curl -L "${URLS[$i]}" -o "Article${formatted_num}.pdf"
          done
          
      - name: Run processing scripts
        run: |
          # Run extraction script
          python extract.py
          
          # Run conversion script
          python convert.py
          
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add amendments.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update zoning amendments data" && git push)
          
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${CLOUDFLARE_PROJECT_NAME}/deployments" \
          -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
          -H "Content-Type: application/json"
